name: tha_palace_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1
  intl_phone_field: ^1.4.2
  font_awesome_flutter: ^8.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/

  fonts:
     - family: Montserrat
       fonts:
       - asset: fonts/Montserrat-Medium.ttf
     - family: Montserrat1
       fonts:
       - asset: fonts/Montserrat-SemiBold.ttf
     - family: Nunito
       fonts:
       - asset: fonts/Nunito-Regular.ttf
     - family: CustomIcons
       fonts:
         - asset: fonts/CustomIcons.ttf



